name: local
description: Local developer environment using local services.
variables:
  API_BASE_URL: http://localhost:4000
  WEB_BASE_URL: http://localhost:3000
  NODE_ENV: development
services:
  - name: web-app
    start: npm run dev --prefix products/web-app
  - name: service-api
    start: npm run dev --prefix products/service-api
checks:
  - Ensure Docker Desktop is running.
  - Install dependencies in both products before starting services.
