name: production
description: Live environment used to capture real revenue.
variables:
  API_BASE_URL: https://api.example.com
  WEB_BASE_URL: https://app.example.com
  NODE_ENV: production
change_management:
  approval: Product + Engineering leads
  rollback_strategy: blue-green
  communication: Announce via release notes derived from the PRD and Experience Blueprint.
monitoring:
  dashboards:
    - https://grafana.example.com/d/prod-web
    - https://grafana.example.com/d/prod-api
  alerts: pagerduty://revenue-stream
